import os

SECRET_KEY = os.environ.get("SUPERSET_SECRET_KEY", "CHANGEME")
SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL", "")

# Connexion PostgreSQL datamart
SQLALCHEMY_EXAMPLES_URI = SQLALCHEMY_DATABASE_URI

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}
